Django/django-podcasting-master/podcasting/urls.py
from django.conf.urls import url
from podcasting.views import ShowListView, ShowDetailView, EpisodeListView, EpisodeDetailView


urlpatterns = [
    url(r"^$", ShowListView.as_view(),
        name="podcasting_show_list"),
    url(r"^(?P<slug>[-\w]+)/$", ShowDetailView.as_view(),
        name="podcasting_show_detail"),
    url(r"^(?P<show_slug>[-\w]+)/archive/$", EpisodeListView.as_view(),
        name="podcasting_episode_list"),
    url(r"^(?P<show_slug>[-\w]+)/(?P<slug>[-\w]+)/$", EpisodeDetailView.as_view(),
        name="podcasting_episode_detail"),
]

Django/django-podcasting-master/podcasting/models.py
from __future__ import unicode_literals

import json
import os

try:
    from urllib2 import urlopen
except ImportError:
    from urllib.request import urlopen

from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
try:
    from django.urls import reverse
except ImportError:
    from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from django.contrib.sites.models import Site

from autoslug import AutoSlugField

from podcasting.managers import EpisodeQuerySet, ShowQuerySet
from podcasting.utils.fields import UUIDField
from podcasting.utils.twitter import can_tweet

# optional external dependencies
try:
    from licenses.models import License
except:
    License = None

try:
    from imagekit.models import ImageSpecField
    from imagekit.processors import ResizeToFill
except ImportError:
    ResizeToFill = ImageSpecField = None

try:
    from easy_thumbnails.fields import ThumbnailerImageField as ImageField
    custom_image_field = True
except ImportError:
    custom_image_field = False

try:
    from photologue.models import Photo
    custom_image_field = True
except ImportError:
    custom_image_field = False

if not custom_image_field:
    try:
        from sorl.thumbnail import ImageField  # noqa
        custom_image_field = True
    except ImportError:
        custom_image_field = False

if not custom_image_field:
    # image-kit uses the standard ImageField as well
    from django.db.models import ImageField  # noqa

if "taggit" in settings.INSTALLED_APPS:
    from taggit.managers import TaggableManager
else:
    def TaggableManager(blank=True):  # noqa
        return None
try:
    import twitter
except ImportError:
    twitter = None  # noqa

try:
    from embed_video.fields import EmbedVideoField
except ImportError:
    EmbedVideoField = None


def get_show_upload_folder(instance, pathname):
    "A standardized pathname for uploaded files and images."
    root, ext = os.path.splitext(pathname)
    return "{0}/podcasts/{1}/{2}{3}".format(
        settings.PODCASTING_IMG_PATH, instance.slug, slugify(root), ext
    )


def get_episode_upload_folder(instance, pathname):
    "A standardized pathname for uploaded files and images."
    root, ext = os.path.splitext(pathname)
    if instance.shows.count() == 1:
        return "{0}/podcasts/{1}/episodes/{2}{3}".format(
            settings.PODCASTING_IMG_PATH, instance.shows.all()[0].slug, slugify(root), ext
        )
    else:
        return "{0}/podcasts/episodes/{1}/{2}{3}".format(
            settings.PODCASTING_IMG_PATH, instance.slug, slugify(root), ext
        )


@python_2_unicode_compatible
class Show(models.Model):
    """
    A podcast show, which has many episodes.
    """
    EXPLICIT_CHOICES = (
        (1, _("yes")),
        (2, _("no")),
        (3, _("clean")),
    )
    uuid = UUIDField(_("id"), unique=True)

    created = models.DateTimeField(_("created"), auto_now_add=True, editable=False)
    updated = models.DateTimeField(_("updated"), auto_now=True, editable=False)
    published = models.DateTimeField(_("published"), null=True, blank=True, editable=False)

    sites = models.ManyToManyField(Site, verbose_name=_('Sites'))

    ttl = models.PositiveIntegerField(
        _("ttl"), default=1440,
        help_text=_("""``Time to Live,`` the number of minutes a channel can be
        cached before refreshing."""))

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="podcast_shows",
        verbose_name=_("owner"),
        on_delete=models.PROTECT,
        help_text=_("""Make certain the user account has a name and e-mail address."""))

    editor_email = models.EmailField(
        _("editor email"), blank=True,
        help_text=_("Email address of the person responsible for the feed's content."))
    webmaster_email = models.EmailField(
        _("webmaster email"), blank=True,
        help_text=_("Email address of the person responsible for channel publishing."))

    if 'licenses' in settings.INSTALLED_APPS:
        license = models.ForeignKey(License, verbose_name=_("license"))
    else:
        license = models.CharField(
            _("license"), max_length=255,
            help_text=_("To publish a podcast to iTunes it is required to set a license type."))

    organization = models.CharField(
        _("organization"), max_length=255,
        help_text=_("Name of the organization, company or Web site producing the podcast."))
    link = models.URLField(_("link"), help_text=_("""URL of either the main website or the
        podcast section of the main website."""))

    enable_comments = models.BooleanField(default=True)

    author_text = models.CharField(
        _("author text"), max_length=255, help_text=_("""
            This tag contains the name of the person or company that is most
            widely attributed to publishing the Podcast and will be
            displayed immediately underneath the title of the Podcast.
            The suggested format is: 'email@example.com (Full Name)'
            but 'Full Name' only, is acceptable. Multiple authors
            should be comma separated."""))

    title = models.CharField(_("title"), max_length=255)
    slug = AutoSlugField(_("slug"), populate_from="title", unique="True")

    subtitle = models.CharField(
        _("subtitle"), max_length=255,
        help_text=_("Looks best if only a few words, like a tagline."))

    # If the show is not on iTunes, many fields may be ignored in your user forms
    on_itunes = models.BooleanField(
        _("iTunes"), default=True,
        help_text=_("Checked if the podcast is submitted to iTunes"))

    description_pretty = models.TextField(
        _("pretty description"), blank=True,
        help_text="May be longer than 4000 characters and contain HTML tags and styling.")

    description = models.TextField(
        _("description"), max_length=4000, help_text=_("""
            This is your chance to tell potential subscribers all about your
            podcast. Describe your subject matter, media format,
            episode schedule, and other relevant info so that they
            know what they'll be getting when they subscribe. In
            addition, make a list of the most relevant search terms
            that you want yourp podcast to match, then build them into
            your description. Note that iTunes removes podcasts that
            include lists of irrelevant words in the itunes:summary,
            description, or itunes:keywords tags. This field can be up
            to 4000 characters."""))

    if 'photologue' in settings.INSTALLED_APPS:
        original_image = models.ForeignKey(Photo, verbose_name=_("image"), default=None, null=True, blank=True, 
        on_delete=models.SET_NULL,
        help_text=_("""
                A podcast must have 1400 x 1400 pixel cover art in JPG or PNG
                format using RGB color space. See our technical spec for
                details. To be eligible for featuring on iTunes Stores,
                choose an attractive, original, and square JPEG (.jpg) or
                PNG (.png) image at a size of 1400x1400 pixels. The image
                will be scaled down to 50x50 pixels at smallest in iTunes.
                For reference see the <a
                href="http://www.apple.com/itunes/podcasts/specs.html#metadata">iTunes
                Podcast specs</a>.<br /><br /> For episode artwork to
                display in iTunes, image must be <a
                href="http://answers.yahoo.com/question/index?qid=20080501164348AAjvBvQ">
                saved to file's <strong>metadata</strong></a> before
                enclosure uploading!"""))
    else:
        original_image = ImageField(
            _("image"), upload_to=get_show_upload_folder, blank=True, help_text=_("""
                A podcast must have 1400 x 1400 pixel cover art in JPG or PNG
                format using RGB color space. See our technical spec for
                details. To be eligible for featuring on iTunes Stores,
                choose an attractive, original, and square JPEG (.jpg) or
                PNG (.png) image at a size of 1400x1400 pixels. The image
                will be scaled down to 50x50 pixels at smallest in iTunes.
                For reference see the <a
                href="http://www.apple.com/itunes/podcasts/specs.html#metadata">iTunes
                Podcast specs</a>.<br /><br /> For episode artwork to
                display in iTunes, image must be <a
                href="http://answers.yahoo.com/question/index?qid=20080501164348AAjvBvQ">
                saved to file's <strong>metadata</strong></a> before
                enclosure uploading!"""))

    if ResizeToFill:
        admin_thumb_sm = ImageSpecField(source="original_image",
                                        processors=[ResizeToFill(50, 50)],
                                        options={"quality": 100})
        admin_thumb_lg = ImageSpecField(source="original_image",
                                        processors=[ResizeToFill(450, 450)],
                                        options={"quality": 100})
        img_show_sm = ImageSpecField(source="original_image",
                                     processors=[ResizeToFill(120, 120)],
                                     options={"quality": 100})
        img_show_lg = ImageSpecField(source="original_image",
                                     processors=[ResizeToFill(550, 550)],
                                     options={"quality": 100})
        img_itunes_sm = ImageSpecField(source="original_image",
                                       processors=[ResizeToFill(144, 144)],
                                       options={"quality": 100})

Django/django-podcasting-master/podcasting/templates/podcasting/_current_episode.html
{% load i18n %}

{% if show %}
    <div class="podcast-episode mod">
        <h2>
            <a href="{{ show.episode_set.current.get_absolute_url }}">
                {{ show.episode_set.current.title }}
            </a>
        </h2>
        <div class="meta">
            <span class="date">
                {{ show.episode_set.current.published|date:"F j, Y" }}
            </span>
            {% for enclosure in show.episode_set.current.enclosure_set.all %}
                {% if enclosure.mime == 'mp3' %}
                    <span class="sep">
                        <a href="{{ enclosure.url }}" class="tiptip download"
                            title="{% trans "to download right click and select 'save link as'" %}">
                            {% trans "Download / Stream" %}
                        </a>
                    </span>
                {% endif %}
            {% endfor %}
            {% if show.episode_set.current.tracklist %}
                <span class="sep">
                    <a href="#tracklist" rel="facebox" class="list">{% trans "Tracklist" %}</a>
                </span>
                <div id="tracklist" class="hidden">
                    <h3>{{ show.episode_set.current.title }} :: {% trans "Tracklist" %}</h3>
                    <div class="tracklist">
                        {{ show.episode_set.current.tracklist|linenumbers|linebreaksbr }}
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="episode-details">
            <a href="{{ show.episode_set.current.img_episode_lg.url }}" rel="facebox" class="episode-thumb">
                <img src="{{ show.episode_set.current.img_episode_sm.url }}"
                    alt="{{ show.episode_set.current.img_episode_sm.name }}"
                    width="{{ show.episode_set.current.img_episode_sm.width }}"
                    height="{{ show.episode_set.current.img_episode_sm.height }}"
                    class="left" />
            </a>
            <h6>{{ show.episode_set.current.subtitle }}</h6>
            {% if show.episode_set.current.description %}
                <p><a href="#details" rel="facebox">{% trans "read more" %}</a></p>
                <div id="details" class="hidden">
                    <div>{{ show.episode_set.current.description }}</div>
                </div>
            {% endif %}
        </div>
    </div>
{% else %}
    <h2 class="coming-soon">{% trans "Coming soon..." %}</h2>
{% endif %}

Django/django-podcasting-master/podcasting/templates/podcasting/_episode_detail.html
{% load i18n %}

{% if episode %}
    <div class="podcast-episode mod">
        <h2>{{ episode.title }}</h2>
        <div class="meta">
            <span class="date">
                {{ episode.published|date:"F j, Y" }}
            </span>
            {% for enclosure in episode.enclosure_set.all %}
                {% if enclosure.mime == 'mp3' %}
                    <span class="sep">
                        <a href="{{ enclosure.url }}" class="tiptip download"
                            title="{% trans "to download right click and select 'save link as'" %}">
                            {% trans "Download / Stream" %}
                        </a>
                    </span>
                {% endif %}
            {% endfor %}
        </div>
        <div class="episode-details">
            <a href="{{ episode.img_episode_lg.url }}" rel="facebox" class="episode-thumb">
                <img src="{{ episode.img_episode_sm.url }}"
                    alt="{{ episode.img_episode_sm.name }}"
                    width="{{ episode.img_episode_sm.width }}"
                    height="{{ episode.img_episode_sm.height }}"
                    class="left" />
            </a>
            <h6>{{ episode.subtitle }}</h6>

            {% if episode.description %}
                <div class="episode-description">{{ episode.description }}</div>
            {% endif %}

            {% if episode.tracklist %}
                <div class="tracklist">
                    <h3>{% trans "Tracklist" %}</h3>
                    {{ episode.tracklist|linenumbers|linebreaksbr }}
                </div>
            {% endif %}
        </div>
    </div>
{% else %}
    <h2 class="coming-soon">{% trans "Coming soon..." %}</h2>
{% endif %}

Django/django-podcasting-master/podcasting/templates/podcasting/_episode_list.html
{% load i18n %}

{% if episode_list %}
    <div class="episode-list">
        {% for episode in episode_list %}
            <div class="podcast-episode mod">
                <h2>{{ episode.title }}</h2>
                <div class="meta">
                    <span class="date">
                        {{ episode.published|date:"F j, Y" }}
                    </span>
                    {% for enclosure in episode.enclosure_set.all %}
                        {% if enclosure.mime == 'mp3' %}
                            <span class="sep">
                                <a href="{{ enclosure.url }}" class="tiptip download"
                                    title="{% trans "to download right click and select 'save link as'" %}">
                                    {% trans "Download / Stream" %}
                                </a>
                            </span>
                        {% endif %}
                    {% endfor %}
                    {% if episode.tracklist %}
                        <span class="sep">
                            <a href="#tracklist-{{ episode.id }}" rel="facebox" class="list">{% trans "Tracklist" %}</a>
                        </span>
                        <div id="tracklist-{{ episode.id }}" class="hidden">
                            <h3>{{ episode.title }} :: {% trans "Tracklist" %}</h3>
                            <div class="tracklist">
                                {{ episode.tracklist|linenumbers|linebreaksbr }}
                            </div>
                        </div>
                    {% endif %}
                </div>
                <div class="episode-details">
                    <a href="{{ episode.img_episode_lg.url }}" rel="facebox" class="episode-thumb">
                        <img src="{{ episode.img_episode_sm.url }}"
                            alt="{{ episode.img_episode_sm.name }}"
                            width="{{ episode.img_episode_sm.width }}"
                            height="{{ episode.img_episode_sm.height }}"
                            class="left" />
                    </a>
                    <h6>{{ episode.subtitle }}</h6>
                    {% if episode.description %}
                        <p><a href="#details-{{ episode.id }}" rel="facebox">{% trans "read more" %}</a></p>
                        <div id="details-{{ episode.id }}" class="hidden">
                            <div>{{ episode.description }}</div>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% else %}
    <h2>{% trans "Coming soon..." %}</h2>
{% endif %}

Django/django-podcasting-master/podcasting/templates/podcasting/_feeds.html
{% load url from future %}
{% load i18n %}

<div class="podcast-feeds">
    subscribe via
    {% if show.feedburner %}
        <a href="{{ show.feedburner }}" target="_blank">{% trans "Feedburner" %}</a>
    {% endif %}
    {% if show.itunes %}
        <a href="{{ show.itunes }}" target="_blank">{% trans "iTunes" %}</a>
    {% endif %}
    <a href="{% url 'podcasts_show_feed_atom' show.slug 'mp3' %}" target="_blank">{% trans "Atom" %}</a>
    <a href="{% url 'podcasts_show_feed_rss' show.slug 'mp3' %}" target="_blank">{% trans "RSS" %}</a>
</div>

Django/django-podcasting-master/podcasting/templates/podcasting/_show_list.html
{% load i18n %}

<div class="podcast-show-list">
    <h2>{% trans "Podcast Shows" %}</h2>

    {% for show in show_list %}
        <div class="podcast-show">
            <h3><a href="{{ show.get_absolute_url }}">{{ show.title }}</a></h3>
            <a href="{{ show.img_show_lg.url }}" rel="facebox">
                <img src="{{ show.img_show_sm.url }}" alt="{{ show.title }}" class="left" />
            </a>
            <h4>{{ show.subtitle }}</h4>
            <p><a href="{{ show.link }}">{{ show.link }}</a></p>
            <div class="show-description">{{ show.description }}</div>
        </div>
    {% empty %}
        <h2>{% trans "There are no shows." %}</h2>
    {% endfor %}
</div>

Django/django-podcasting-master/podcasting/templates/podcasting/admin_thumbnail_css.html
{% load i18n %}

{% if original_image %}
    <a href="{{ original_image.url }}" target="_blank">
        <img src="{{ original_image.url }}" style="height: 50px; width: 50px" />
    </a>
{% else %}
    <p>{% trans "No image" %}</p>
{% endif %}

Django/django-podcasting-master/podcasting/templates/podcasting/admin_thumbnail_easy-thumbnails.html
{% load i18n thumbnail %}


{% if original_image %}
    <a href="{{ original_image.url }}" target="_blank">
        <img src="{% thumbnail original_image "240x240" %}"/>
    </a>
{% else %}
    <p>{% trans "No image" %}</p>
{% endif %}

Django/django-podcasting-master/podcasting/templates/podcasting/admin_thumbnail_imagekit.html
<a href="{{ thumb_lg_url }}" target="_blank">
    <img src="{{ thumb_sm_url }}">
</a>

Django/django-podcasting-master/podcasting/templates/podcasting/admin_thumbnail_sorl.html
{% load thumbnail i18n %}

{% thumbnail original_image.url "30x30" as im %}
    <a href="{{ im.url }}" target="_blank">
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"/>
    </a>
{% empty %}
    <p>{% trans "No image" %}</p>
{% endthumbnail %}

Django/django-podcasting-master/podcasting/templates/podcasting/current_episode.html
{% extends "podcasting/podcasting_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Current Edition" %}{% endblock %}

{% block body_class %}page-current-episode{% endblock %}

{% block content %}
    {% include "podcasting/_current_episode.html" %}
    {% block current_episode_extra %}{% endblock %}
{% endblock %}

Django/django-podcasting-master/podcasting/templates/podcasting/episode_list.html
{% extends "podcasting/podcasting_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Archive" %}{% endblock %}

{% block body_class %}page-episode-list{% endblock %}

{% block content %}
    {% include "podcasting/_episode_list.html" %}
    {% block episode_list_extra %}{% endblock %}
{% endblock %}

Django/django-podcasting-master/podcasting/templates/podcasting/podcasting_base.html
{% extends "site_base.html" %}

Django/django-podcasting-master/podcasting/templates/podcasting/show_detail.html
{% extends "podcasting/podcasting_base.html" %}

{% block head_title %}{{ show.title }}{% endblock %}

{% block body_class %}page-show-detail{% endblock %}

{% block content %}
    {% include "podcasting/_show_detail.html" %}
    {% block show_detail_extra %}{% endblock %}
{% endblock %}

Django/django-podcasting-master/podcasting/templates/podcasting/show_list.html
{% extends "podcasting/podcasting_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Podcast Shows" %}{% endblock %}

{% block body_class %}page-show-list{% endblock %}

{% block content %}
    {% include "podcasting/_show_list.html" %}
    {% block show_list_extra %}{% endblock %}
{% endblock %}